add License header according to standard template
intel/confidential-cloud-native-primitives pull request #78
Opened 2023-07-21 02:11 UTC by hairongchen

Add Apache-2.0 license info

Signed-off-by: Hairong Chen hairong.chen@intel.com

2023-07-21 02:15 UTC, Ruoyu-y requested changes

2023-07-21 02:15 UTC, Ruoyu-y commented on service/quote-server/Makefile
> +
remove the first empty line?

2023-07-21 02:29 UTC, hwang37 approved these changes
LGTM

2023-07-21 02:31 UTC, Ruoyu-y approved these changes
LGTM

2023-07-24 00:59 UTC, kenplusplus approved these changes
LGTM

2023-07-24 00:59 UTC, merged